  const jokes = [
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "Did you hear about the restaurant on the moon? Great food, but no atmosphere.",
    "What do you call a fake noodle? An impasta.",
    "How do you organize a space party? You planet.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "I'm reading a book about anti-gravity. It's impossible to put down.",
    "I used to be a personal trainer, but I had too many commitments to work out.",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "I wouldn't buy anything with velcro. It's a total rip-off.",
    "What's the best time to go to the dentist? Tooth-hurty.",
    "Did you hear about the guy who invented Lifesavers? They say he made a mint.",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What do you call a bear with no teeth? A gummy bear.",
    "How does a penguin build its house? Igloos it together.",
    "Why did the math book look sad? Because it had too many problems.",
    "What did the grape say when it got stepped on? Nothing, it just let out a little wine.",
    "I used to be addicted to the hokey pokey, but I turned myself around.",
    "What kind of shoes do ninjas wear? Sneakers.",
    'What did one wall say to the other wall? "I\'ll meet you at the corner."',
    "How do you make a tissue dance? Put a little boogie in it.",
    "Why don't scientists trust stairs? Because they're always up to something.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Did you hear about the cheese factory explosion? There was nothing left but de-brie.",
    "What's orange and sounds like a parrot? A carrot.",
    "What do you call a fish with no eyes? Fsh.",
    "Why couldn't the bicycle stand up by itself? It was two tired.",
    "How do you catch a squirrel? Climb a tree and act like a nut.",
    "Did you hear about the guy who invented the knock-knock joke? He won the no-bell prize.",
    "I'm on a seafood diet. I see food and I eat it.",
    "Why did the invisible man turn down the job offer? He couldn't see himself doing it.",
    "I used to play piano by ear, but now I use my hands.",
    "What do you call a deer with no eyes? No idea (no-eye deer).",
    "How do you make holy water? You boil the hell out of it.",
    "What did the buffalo say to his son when he left for college? Bison.",
    "What do you call a cow with no legs? Ground beef.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "I thought about going on an all-almond diet. But that's just nuts.",
    "What's the difference between a poorly dressed man on a trampoline and a well-dressed man on a trampoline? Attire.",
    "What do you call a belt made of watches? A waist of time.",
    "How do you make a lemon drop? Just let it fall.",
    "What's Forrest Gump's password? 1forrest1",
    "I only know 25 letters of the alphabet. I don't know y.",
    "Why do fathers take an extra pair of socks when they go golfing? In case they get a hole in one.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "What do you call a fish wearing a crown? King of the sea.",
    "What's the best way to watch a fly fishing tournament? Live stream.",
    "What do you call a dog that can do magic? A labracadabrador.",
    "I had a joke about time travel, but you didn't like it.",
    "What's the difference between a hippo and a zippo? One is really heavy and the other is a little lighter.",
    "Did you hear about the kidnapping at the playground? They woke up.",
    "What's the difference between a pizza and my jokes? My jokes can't be delivered.",
    "Why do melons have weddings? Because they cantaloupe.",
    "What did the drummer name his twin daughters? Anna one, Anna two.",
    "How many tickles does it take to make an octopus laugh? Ten-tickles.",
    "What concert costs just 45 cents? 50 Cent featuring Nickelback.",
    "Did you hear about the restaurant called Karma? There's no menu: You get what you deserve.",
    "Why did the stadium get hot after the game? All the fans left.",
    "I used to be a baker, but I couldn't make enough dough.",
    "What's brown and sticky? A stick.",
    "Why can't you give Elsa a balloon? Because she'll let it go.",
    'I asked the librarian if the library had any books on paranoia. She whispered, "They\'re right behind you."',
    "What do you call a pony with a sore throat? A little hoarse.",
    "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
    "Why can't you explain puns to kleptomaniacs? They always take things literally.",
    "What do you call a bee that can't make up its mind? A maybe.",
    "My wife told me to stop acting like a flamingo. I had to put my foot down.",
    "I was wondering why the baseball was getting bigger. Then it hit me.",
    "What do you call someone with no body and no nose? Nobody knows.",
    "What do you call a parade of rabbits hopping backwards? A receding hare-line.",
    'Why can\'t you hear a pterodactyl go to the bathroom? Because the "p" is silent.',
    "I asked my dog what's two minus two. He said nothing.",
    'Yesterday I saw a guy spill all his Scrabble letters on the road. I asked him, "What\'s the word on the street?"',
    'Whenever I try to eat healthy, a chocolate bar looks at me and says, "I\'m here for you."',
    "What did the left eye say to the right eye? Between you and me, something smells.",
    "What do you call a boomerang that doesn't come back? A stick.",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Did you hear about the man who fell into an upholstery machine? He's fully recovered.",
    "I don't trust stairs because they're always up to something.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "Did you hear about the claustrophobic astronaut? He just needed some space.",
    "What's a pirate's favorite letter? You might think it's R, but his first love is the C.",
    "Why don't oysters donate to charity? Because they're shellfish.",
    "I made a pencil with two erasers. It was pointless.",
    "How many apples grow on a tree? All of them.",
    "What do you call a dictionary on drugs? High definition.",
    "I once got fired from a canned juice company. Apparently I couldn't concentrate.",
    "What do you call a sad cup of coffee? Depresso.",
    "Where do boats go when they're sick? To the dock.",
    "What's E.T. short for? Because he's got little legs.",
    "Did you hear about the guy who invented the doorbell? He won the No-bell prize.",
    "When does a joke become a dad joke? When it becomes apparent.",
    'My friend keeps saying "cheer up, it could be worse, you could be stuck underground in a hole full of water." I know he means well.',
    "Did you hear about the circus fire? It was in tents.",
    "I'm on a whiskey diet. I've lost three days already.",
    "I couldn't figure out how to put my seatbelt on. Then it clicked.",
    "Want to hear a joke about construction? I'm still working on it.",
    "I'm no good at math, but I know that 7 days without pizza makes one weak.",
    "I made a pun about the wind but it blows.",
    "I would tell you a joke about an elevator, but it's an uplifting experience.",
    "I'm afraid for the calendar. Its days are numbered.",
    "What did one hat say to the other hat? Stay here, I'm going on ahead!",
    "I don't trust people who do acupuncture. They're back stabbers.",
    "I tried to catch some fog earlier. I mist.",
  ];

  function getJoke() {
    const index = Math.floor(Math.random() * jokes.length);
    return jokes[index];
  }


 